
PUT http://127.0.0.1:8000/movies/1 HTTP/1.1
Content-Type: application/json

{
    "title":"The Shawshank Redemption 2",
    "year":"1994", 
    "actors":"Tim Robbins, Morgan Freeman"
}

DELETE  http://localhost:8000/movies/5

DELETE http://localhost:8000/movies

POST http://localhost:8000/movies
Content-Type: application/json

{
    "title":"The Shawshank Redemption",
    "year":"1994", 
    "actors":"Tim Robbins, Morgan Freeman"
}